apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: sv-backstages
  name: sv-backstages
  namespace: backstages
spec:
  ports:
    - port: 7007
      name: http
      protocol: TCP
      targetPort: 7007
  selector:
    app: backstages
  type: NodePort
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-backstages
  namespace: backstages
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: backstages
  namespace: backstages
  name: backstages
spec: 
  replicas: 1
  revisionHistoryLimit: 0
  selector: 
    matchLabels: 
      app: backstages
  template: 
    metadata: 
      labels: 
        app: backstages
    spec:
      containers: 
        - image: us-east1-docker.pkg.dev/arquitectura-digital-everis/regdev01/backstage-da:1.10
          imagePullPolicy: Always
          name: backstages
          envFrom:
          - secretRef:
              name: secret-cnx-devops
          ports: 
            - containerPort: 7007
          resources:
              limits:
                memory: 256Mi
          volumeMounts:
          - mountPath: /vol
            subPath: vol
            name: docs
      volumes:
      - name: docs
        persistentVolumeClaim:
          claimName: pvc-backstages
      restartPolicy: Always
  
